#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yuto Matsushima
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

ans = 0.0
for line in sys.stdin:
    ans += float(line)**2

ans = math.sqrt(ans)

if ans.is_integer():
    print(int(ans))
else:
    print(ans)
