#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yuto Matsushima
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

def calculate(lines):
    ans = 0.0
    for line in lines:
        ans += float(line)**2
    return math.sqrt(ans)

def tonum(value):
    if value.is_integer():
        return int(value)
    else:
        return value

if __name__ == '__main__':
    result = calculate(sys.stdin)
    print(tonum(result))
