#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yuto Matsushima
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

s = 0.0
for line in sys.stdin:
    s += float(line)**2

print(math.sqrt(s))
